// Types of Actions

// Login
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE= 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

// Friend Login
export const FRIEND_LOGIN = 'FRIEND_LOGIN';
export const FRIEND_LOGIN_SUCCESS = 'FRIEND_LOGIN_SUCCESS';
export const FRIEND_LOGIN_FAILURE= 'FRIEND_LOGIN_FAILURE';

// Sign Up
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';
export const USER_ADD_DEFAULT_RESTAURANTS = 'USER_ADD_DEFAULT_RESTAURANTS';
export const USER_ADD_DEFAULT_RESTAURANTS_SUCCESS = 'USER_ADD_DEFAULT_RESTAURANTS_SUCCESS';
export const USER_ADD_DEFAULT_RESTAURANTS_FAILURE = 'USER_ADD_DEFAULT_RESTAURANTS_FAILURE';

// Forget Password
export const SEND_FORGET_PASSWORD_EMAIL = 'SEND_FORGET_PASSWORD_EMAIL';
export const SEND_FORGET_PASSWORD_EMAIL_SUCCESS = 'SEND_FORGET_PASSWORD_EMAIL_SUCCESS';
export const SEND_FORGET_PASSWORD_EMAIL_FAILURE = 'SEND_FORGET_PASSWORD_EMAIL_FAILURE';

// Reset Password
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAILURE = 'USER_RESET_PASSWORD_FAILURE';

// Validate Reset Password
export const VALIDATE_RESET_PASSWORD = 'VALIDATE_RESET_PASSWORD';
export const VALIDATE_RESET_PASSWORD_SUCCESS = 'VALIDATE_RESET_PASSWORD_SUCCESS';
export const VALIDATE_RESET_PASSWORD_FAILURE = 'VALIDATE_RESET_PASSWORD_FAILURE';

// Restaurant
// Add Restaurant
export const OPEN_ADD_RESTAURANT_MODAL = 'OPEN_ADD_RESTAURANT_MODAL';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS';
export const ADD_RESTAURANT_FAILURE = 'ADD_RESTAURANT_FAILURE';
export const CLOSE_ADD_RESTAURANT_MODAL = 'CLOSE_ADD_RESTAUANT_MODAL';

// Fetch Restaurant List
export const FETCH_RESTAURANT_LIST = 'FETCH_RESTAURANT_LIST';
export const FETCH_RESTAURANT_LIST_SUCCESS = 'FETCH_RESTAURANT_LIST_SUCCESS';
export const FETCH_RESTAURANT_LIST_FAILURE = 'FETCH_RESTAURANT_LIST_FAILURE';

// Fetch Restaurant
export const FETCH_RESTAURANT_TOTAL = 'FETCH_RESTAURANT_TOTAL';
export const FETCH_RESTAURANT_TOTAL_SUCCESS = 'FETCH_RESTAURANT_TOTAL_SUCCESS';
export const FETCH_RESTAURANT_TOTAL_FAILURE = 'FETCH_RESTAURANT_TOTAL_FAILURE';

// Fetch Restaurant Name
export const FETCH_RESTAURANT_NAMES = 'FETCH_RESTAURANT_NAMES';
export const FETCH_RESTAURANT_NAMES_SUCCESS = 'FETCH_RESTAURANT_NAMES_SUCCESS';
export const FETCH_RESTAURANT_NAMES_FAILURE = 'FETCH_RESTAURANT_NAMES_FAILURE';

// Update Restaurant
export const OPEN_UPDATE_RESTAURANT_MODAL = 'OPEN_UPDATE_RESTAURANT_MODAL';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE';
export const CLOSE_UPDATE_RESTAURANT_MODAL = 'CLOSE_UPDATE_RESTAURANT_MODAL';

// Delete Restaurant
export const OPEN_DELETE_RESTAURANT_MODAL = 'OPEN_DELETE_RESTAURANT_MODAL';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';
export const DELETE_RESTAURANT_FAILURE = 'DELETE_RESTAURANT_FAILURE';
export const CLOSE_DELETE_RESTAURANT_MODAL = 'CLOSE_DELETE_RESTAURANT_MODAL';


// Collections
// Fetch  Colletions
export const FETCH_COLLECTION_LIST = 'FETCH_COLLECTION_LIST';
export const FETCH_COLLECTION_LIST_SUCCESS = 'FETCH_COLLECTION_LIST_SUCCESS';
export const FETCH_COLLECTION_LIST_FAILURE = 'FETCH_COLLECTION_LIST_FAILURE';

// Add  Colletions
export const OPEN_ADD_COLLECTION_MODAL = 'OPEN_ADD_COLLECTION_MODAL';
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_FAILURE = 'ADD_COLLECTION_FAILURE';
export const CLOSE_ADD_COLLECTION_MODAL = 'CLOSE_ADD_COLLECTION_MODAL';

// Delete  Colletions
export const OPEN_DELETE_COLLECTION_MODAL = 'OPEN_DELETE_COLLECTION_MODAL';
export const DELETE_COLLECTION = 'DELETE_COLLECTIONS';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTIONS_SUCCESS';
export const DELETE_COLLECTION_FAILURE = 'DELETE_COLLECTIONS_FAILURE';
export const CLOSE_DELETE_COLLECTION_MODAL = 'CLOSE_DELETE_COLLECTION_MODAL';

// Add Restaurants to Collection
export const ADD_RESTAURANT_TO_COLLECTION = 'ADD_RESTAURANT_TO_COLLECTION';
export const ADD_RESTAURANT_TO_COLLECTION_SUCCESS = 'ADD_RESTAURANT_TO_COLLECTION_SUCCESS';
export const ADD_RESTAURANT_TO_COLLECTION_FAILURE = 'ADD_RESTAURANT_TO_COLLECTION_FAILURE';

// Delete Restaurants from Collection
export const DELETE_RESTAURANT_FROM_COLLECTION = 'DELETE_RESTAURANT_FROM_COLLECTION';
export const DELETE_RESTAURANT_FROM_COLLECTION_SUCCESS = 'DELETE_RESTAURANT_FROM_COLLECTION_SUCCESS';
export const DELETE_RESTAURANT_FROM_COLLECTION_FAILURE = 'DELETE_RESTAURANT_FROM_COLLECTION_FAILURE';


// Friend
// Fetch Friends
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_FAILURE = 'FETCH_FRIENDS_FAILURE';

// Add Friends
export const OPEN_ADD_FRIEND_MODAL = 'OPEN_ADD_FRIEND_MODAL';
export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';
export const CLOSE_ADD_FRIEND_MODAL = 'CLOSE_ADD_FRIEND_MODAL';

// Delete friends
export const OPEN_DELETE_FRIEND_MODAL = 'OPEN_DELETE_FRIEND_MODAL';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';
export const DELETE_FRIEND_FAILURE = 'DELETE_FRIEND_FAILURE';
export const CLOSE_DELETE_FRIEND_MODAL = 'CLOSE_DELETE_FRIEND_MODAL';
