name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: yarn test
        run: |
          yarn install --frozen-lockfile
          yarn test
